### ISSUE TITLE
Initalize node error

### ISSUE THREAD

**Issue by Peeliye** [nodemasterpro/deploy-node-allora#1]
**It started out as a Make error, caused by the go version, which I solved by reinstalling go, and then when I got to the initialization this one came up with the error.**

- Linux version: Ubuntu 22.04.4 LTS
- Go version: go1.22.4 linux/amd64

![image](https://github.com/nodemasterpro/deploy-node-allora/assets/30661108/39c04a76-a047-4f0c-8c61-6ac6b6167e4b)

Please fix it, thanks for you.

**Comment by nasbuild** [comment]
Check that the go version you have is version 1.22.4 or higher by typing this command:

go version

Then uninstall the node with the removal script:

ansible-playbook remove_validator_node_allora.yml 

then start the installation again.

**Comment by FolicAcid** [comment]
I got the same error.my go version is 1.22.4 I reinstalled but still get this error. any solutions yet?
