### ISSUE TITLE
worker update

### ISSUE THREAD

**Issue by 0xHawre** [nodemasterpro/deploy-node-allora#2]
gm gm worker got updated new fucet  is this still working i mean the worker not node

**Comment by 0xHawre** [comment]
<img width="1442" alt="Screenshot 2024-07-19 at 5 42 26 PM" src="https://github.com/user-attachments/assets/6f88247c-0397-466e-a15a-ca61259c0477">

**Comment by nodemasterpro** [comment]
I have just published an update to my script with the provision of prediction models. Feel free to update the project ( git pull) and tester again.
