### ISSUE TITLE
usage of v0.0.10

### ISSUE THREAD

**Issue by dhairya1008** [nodemasterpro/deploy-node-allora#3]
hey bro, you're using v0.0.10 in your script that pulls the allora repo to local. Please fix it to use to `latest` else the validator node might not work properly.

**Comment by nasbuild** [comment]
Hi, I am not using version v.0.0.10 but release v0.2.7 for the edgenet validator node. I compile the binary myself from the sources. For the new script I would use version v0.2.11 for the testnet_v2 validator node according to the documentation.
